# Generated by Django 5.2.7 on 2025-11-17 22:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mockapi', '0003_remove_customer_wishlist_alter_customer_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='WishListItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mockapi.customer')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mockapi.product')),
            ],
        ),
        migrations.AddField(
            model_name='customer',
            name='wishlist',
            field=models.ManyToManyField(related_name='wishlists', through='mockapi.WishListItem', to='mockapi.product'),
        ),
    ]
