# Generated by Django 5.2.7 on 2025-11-23 19:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mockapi', '0006_alter_cartitem_qty'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='customer',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='mockapi.customer'),
            preserve_default=False,
        ),
    ]
