# Generated by Django 5.2.7 on 2025-11-24 16:12

import django.db.models.deletion
import mockapi.models.product
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mockapi', '0008_remove_cartitem_cart_alter_cartitem_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image_url',
            field=models.ImageField(default='product/default.jpg', storage=mockapi.models.product.OverwriteStorage(), upload_to=mockapi.models.product.product_image_path),
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_address', models.TextField()),
                ('delivery_contact', models.TextField()),
                ('delivery_name', models.TextField()),
                ('delivery_comment', models.TextField()),
                ('total_cost', models.FloatField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_paid', models.BooleanField(default=False)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='mockapi.customer')),
                ('delivery_status', models.ForeignKey(on_delete=django.db.models.deletion.SET_NULL, to='mockapi.deliverystatus')),
                ('order_status', models.ForeignKey(on_delete=django.db.models.deletion.SET_NULL, to='mockapi.orderstatus')),
            ],
        ),
    ]
