# Generated by Django 5.2.7 on 2025-11-25 09:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mockapi', '0009_alter_product_image_url_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.IntegerField(default=1)),
                ('black_price', models.FloatField()),
                ('final_price', models.FloatField()),
                ('total_cost', models.FloatField()),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mockapi.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.SET_NULL, to='mockapi.product')),
            ],
        ),
    ]
